export const productActions = {
  ADD_PRODUCT_CART: 'product/ADD_PRODUCT_CART',
  CHANGED_PRODUCT: 'product/CHANGED_PRODUCT',
  CHANGED_QUANTITY: 'product/CHANGED_QUANTITY',
  RESET_PRODUCT: 'product/RESET_PRODUCT',
  UPDATE_TOTAL: 'product/UPDATE_TOTAL'
}
