export const productActions = {
  CHANGED_PRODUCT: 'product/CHANGED_PRODUCT',
  CHANGED_QUANTITY: 'product/CHANGED_QUANTITY',
  ADD_PRODUCT_CART: 'product/ADD_PRODUCT_CART',
  UPDATE_TOTAL: 'product/UPDATE_TOTAL'
}
